title: CSP.guru (BETA)
email: tim.troendle@usys.ethz.ch
description: >-
  This site hosts a database of CSP plants.
url: "https://csp.guru/" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  timtroendle

# Build settings
data_dir: csp-guru
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
